---
title: "Ausländerquote"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Daten einlesen}
library(readxl)
library(maps)
library(mapdata)
library(maptools)
library(rgdal)
library(ggmap)
library(ggplot2)
library(rgeos)
library(broom)
library(plyr)
GE2015_constituency_results <- read.csv("C:/Users/loebu/OneDrive/Anfängerpraktikum/2015-UK-general-election-data-results - CSV/RESULTS FOR ANALYSIS.csv")
GE2017_constituency_result <- read.csv("C:/Users/loebu/OneDrive/Anfängerpraktikum/HoC-GE2017-constituency-results.csv")
GE2017_result_by_candidate <- read.csv("C:/Users/loebu/OneDrive/Anfängerpraktikum/HoC-GE2017-results-by-candidate.csv")
GE2019_constituency_result <- read.csv("C:/Users/loebu/OneDrive/Anfängerpraktikum/HoC-GE2019-results-by-constituency-csv.csv")
GE2019_result_by_candidate <- read.csv("C:/Users/loebu/OneDrive/Anfängerpraktikum/HoC-GE2019-results-by-candidate-csv.csv")
population_by_age <- read_excel("C:/Users/loebu/OneDrive/Anfängerpraktikum/population-by-age_anders_sortiert.xlsx")
population_by_age_smaller_2016 <- population_by_age[population_by_age$Date == 2016, c(1:9, 11)]
population_by_age_smaller_2016 <- spread(population_by_age_smaller_2016, key = colnames(population_by_age_smaller_2016) [1], 
                                         value = colnames(population_by_age_smaller_2016) [10])
Leave_vote_constituency <- read.csv("C:/Users/loebu/OneDrive/Anfängerpraktikum/Revised estimates of leave vote in Westminster constituencies - demog_based_estimates.csv")
shapefile.2 <- readOGR(dsn="C:/Users/loebu/OneDrive/Anfängerpraktikum", layer="Local_Authority_Districts__April_2019__UK_BUC_v2")
mapdata.2 <- tidy(shapefile.2, region="LAD19NM")
Neuwaehler <- read_excel("C:/Users/loebu/OneDrive/Anfängerpraktikum/Neuwähler.xlsx")
```

```{r Ausländerquote}
GE2017_result123 <- GE2017_constituency_result[ , c(1, 3, 5:6, 12:13, 16:28)]
GE2017_result123$votes_1 <- (GE2017_result123$alliance + GE2017_result123$sdlp + GE2017_result123$snp + GE2017_result123$ld + GE2017_result123$pc +
                               GE2017_result123$green + GE2017_result123$sf) / GE2017_result123$valid_votes
GE2017_result123$votes_2 <- (GE2017_result123$uup + GE2017_result123$lab + GE2017_result123$dup) / GE2017_result123$valid_votes
GE2017_result123$votes_3 <- (GE2017_result123$con + GE2017_result123$ukip) / GE2017_result123$valid_votes
GE2017_result123$votes_others <- 1- GE2017_result123$votes_1 - GE2017_result123$votes_2 - GE2017_result123$votes_3
GE2017_result123 <- GE2017_result123[ , -c(7:19)]
GE2019_result123 <- GE2019_constituency_result[ , c(1, 3, 5:6, 15:16, 19:31)]
GE2019_result123$votes_1 <- (GE2019_result123$alliance + GE2019_result123$sdlp + GE2019_result123$snp + GE2019_result123$ld + GE2019_result123$pc +
                               GE2019_result123$green + GE2019_result123$sf) / GE2019_result123$valid_votes
GE2019_result123$votes_2 <- (GE2019_result123$uup + GE2019_result123$lab + GE2019_result123$dup) / GE2019_result123$valid_votes
GE2019_result123$votes_3 <- (GE2019_result123$con + GE2019_result123$brexit) / GE2019_result123$valid_votes
GE2019_result123$votes_others <- 1- GE2019_result123$votes_1 - GE2019_result123$votes_2 - GE2019_result123$votes_3
GE2019_result123 <- GE2019_result123[ , -c(7:19)]
GE2017_result123_auslaenderq <- GE2017_result123
GE2017_result123_auslaenderq$adj_electorate <- GE2017_result123$electorate - (285000/sum(GE2017_result123$electorate))*GE2017_result123$electorate
GE2019_result123_auslaenderq <- GE2019_result123
GE2019_result123_auslaenderq$adj_electorate <- GE2019_result123$electorate - (233000/sum(GE2019_result123$electorate))*GE2019_result123$electorate
Neuwaehler_2017 <- Neuwaehler[Neuwaehler$Year == 2017, c(1:3, 7)]
Neuwaehler_2019 <- Neuwaehler[Neuwaehler$Year == 2019, c(1:3, 7)]
colnames(GE2017_result123_auslaenderq) [1] <- "Constituency.ID"
colnames(GE2019_result123_auslaenderq) [1] <- "Constituency.ID"
colnames(Neuwaehler_2017) [1] <- "Constituency.ID"
colnames(Neuwaehler_2019) [1] <- "Constituency.ID"
GE2017_auslaenderq <- join(GE2017_result123_auslaenderq, Neuwaehler_2017, by = "Constituency.ID")
GE2019_auslaenderq <- join(GE2019_result123_auslaenderq, Neuwaehler_2019, by = "Constituency.ID")
GE2017_auslaenderq$auslaenderq <- 1- GE2017_auslaenderq$adj_electorate / GE2017_auslaenderq$`Gesamtbevölkerung über 18`
GE2019_auslaenderq$auslaenderq <- 1- GE2019_auslaenderq$adj_electorate / GE2019_auslaenderq$`Gesamtbevölkerung über 18`
GE2017_auslaenderq$auslaenderq[which(GE2017_auslaenderq$auslaenderq < 0)] <- 0
GE2019_auslaenderq$auslaenderq[which(GE2019_auslaenderq$auslaenderq < 0)] <- 0
```

```{r Grafiken}
ggplot(data = GE2017_auslaenderq, aes(x = auslaenderq, y = votes_1)) +
  geom_point() +
  geom_smooth(method = "lm")
ggplot(data = GE2017_auslaenderq, aes(x = auslaenderq, y = votes_2)) +
  geom_point() +
  geom_smooth(method = "lm")
ggplot(data = GE2017_auslaenderq, aes(x = auslaenderq, y = votes_3)) +
  geom_point() +
  geom_smooth(method = "lm")
ggplot(data = GE2019_auslaenderq, aes(x = auslaenderq, y = votes_1)) +
  geom_point() +
  geom_smooth(method = "lm")
ggplot(data = GE2019_auslaenderq, aes(x = auslaenderq, y = votes_2)) +
  geom_point() +
  geom_smooth(method = "lm")
ggplot(data = GE2019_auslaenderq, aes(x = auslaenderq, y = votes_3)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r Lineare Modelle}
m17_auslaenderq_1 <- lm(data = GE2017_auslaenderq, votes_1 ~ auslaenderq)
summary(m17_auslaenderq_1)
m17_auslaenderq_2 <- lm(data = GE2017_auslaenderq, votes_2 ~ auslaenderq)
summary(m17_auslaenderq_2)
m17_auslaenderq_3 <- lm(data = GE2017_auslaenderq, votes_3 ~ auslaenderq)
summary(m17_auslaenderq_3)
m19_auslaenderq_1 <- lm(data = GE2019_auslaenderq, votes_1 ~ auslaenderq)
summary(m19_auslaenderq_1)
m19_auslaenderq_2 <- lm(data = GE2019_auslaenderq, votes_2 ~ auslaenderq)
summary(m19_auslaenderq_2)
m19_auslaenderq_3 <- lm(data = GE2019_auslaenderq, votes_3 ~ auslaenderq)
summary(m19_auslaenderq_3)
```